#!/usr/bin/env python
########################################################################
#
#  This script is used to dump the current entries in the database
# to the console.
#
#  Kyle Fransham, November 2011
#
########################################################################

import ConfigParser

try:
    import sqlite3
except:
    from pysqlite2 import dbapi2 as sqlite3

config = ConfigParser.ConfigParser()
config.read('/etc/torque-kvm.conf')
torque_home=config.get("torque","torque_home")
dbfile=torque_home + "/net/network.db"

conn=sqlite3.connect(dbfile)
c=conn.cursor()
c.execute('select * from reservations')	

print "\n\n*************************************************************************"
print "host\t\t\t ip \t\t mac \t\t\t inuse"
print "*************************************************************************"
try:
	while 1:
		(host,ip,mac,inuse) = c.next()
		print host + "\t "+ip+"\t "+mac+"\t "+str(inuse)
except StopIteration:
	pass;
print "*************************************************************************\n\n"		
c.close()	
